apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-pv-3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  capacity:
    storage: 20Mi
  hostPath:
    path: /home/flarei
