
require 'rake/testtask'
require 'ci/reporter/rake/test_unit'

task :default => [:test]

envargs = "-u FLARE_INDEX_SERVER -u FLARE_INDEX_SERVER_PORT"
envargs = ""

task :default => [:test]

Rake::TestTask.new do |test|
  test.libs << './lib' << '../lib'
  test.test_files = Dir['test/unit/**/*_test.rb', 'test/integration/**/*_test.rb', 'test/system/**/*_test.rb']
  test.verbose = true
  test.ruby_opts = ['-r', 'rubygems']
end

task :stress do
  tests.each do |test|
    options = "--verbose"
    sh "env #{envargs} FLARE_TOOLS_STRESS_TEST=yes ruby #{test}_test.rb #{options}"
  end
end

task :clean do
 sh "rm -rf work/test*"
 sh "rm -f *~"
 sh "rm -f /tmp/flare[id].*.conf"
end

task :killall do
 sh "pkill /usr/local/bin/flarei"
 sh "pkill /usr/local/bin/flared"
end

