
require 'rake/testtask'
require 'ci/reporter/rake/test_unit_loader'

envargs = "-u FLARE_INDEX_SERVER -u FLARE_INDEX_SERVER_PORT"
envargs = ""

task :default => [:test]

Rake::TestTask.new do |test|
  test.libs << './lib' << '../lib'
  test.test_files = Dir['test/unit/**/*_test.rb', 'test/integration/**/*_test.rb', 'test/system/**/*_test.rb']
  test.verbose = true
  test.ruby_opts = ['-r', 'rubygems']
end

task :help do
  print <<EOS
Examples:
  run a specific test script
  > rake TEST=testname_test.rb
  run a specific test
  > rake TESTOPTS=--name=test_mytest1
  run tests with --verbose
  > rake TESTOPTS=--verbose
  run stress tests
  > rake FLARE_TOOLS_STRESS_TEST=yes
EOS
end

task :clean do
 sh "rm -rf work/test*"
 sh "rm -f *~"
 sh "rm -f /tmp/flare[id].*.conf"
end

task :killall do
 sh "pkill /usr/local/bin/flarei"
 sh "pkill /usr/local/bin/flared"
end

