
task :default => [:test]

tests = ["daemon", "stats", "cluster", "logger", "node", "cli", "util", "partition", "bwlimit"]
envargs = "-u FLARE_INDEX_SERVER -u FLARE_INDEX_SERVER_PORT"

if ENV.has_key? "TESTS"
  tests = ENV["TESTS"].split(' ')
end

tests.each do |test|
  task test.to_sym do |t|
    options = "--verbose"
    sh "env #{envargs} ruby #{t.name}_test.rb #{options}"
  end
end

task :test => tests.map {|x| x.to_sym}

task :stress do
  tests.each do |test|
    options = "--verbose"
    sh "env #{envargs} FLARE_TOOLS_STRESS_TEST=yes ruby #{test}_test.rb #{options}"
  end
end

task :clean do
 sh "rm -rf work/test*"
 sh "rm -f *~"
 sh "rm -f /tmp/flare[id].*.conf"
end

task :killall do
 sh "pkill /usr/local/bin/flarei"
 sh "pkill /usr/local/bin/flared"
end

