run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - unused
    - ineffassign
    - typecheck
    - goimports
    - misspell
    - staticcheck
    - gosimple
    - stylecheck

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/gree/flare-tools
  govet:
    enable:
      - shadow  # replaces check-shadowing
  maligned:
    suggest-new: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: test/
      linters:
        - errcheck
    - path: cmd/
      linters:
        - errcheck
    - text: "Error return value of.*is not checked"
      linters:
        - errcheck
    - text: "should have comment or be unexported"
      linters:
        - revive