back-log = 8192
data-dir = /home/flare
index-server-name = flarei.default.svc.cluster.local
index-server-port = 13300
log-facility = local5
max-connection = 32768
mutex-slot = 1024
proxy-concurrency = 16
reconstruction-interval = 0
reconstruction-bwlimit = 10000
server-port = 13301
stack-size = 128
storage-ap = 4
storage-fp = 16
storage-bucket-size = 33554432
storage-large = true
storage-type = tch
thread-pool-size = 16
