data-dir = /home/flare
log-facility = local5
max-connection = 512
monitor-threshold = 10
monitor-interval = 1
server-name = flarei.default.svc.cluster.local
server-port = 13300
thread-pool-size = 8
key-hash-algorithm = jenkins
