data-dir = /tmp/flare-prod-slave-2
index-servers = flarei-prod:12120
log-facility = local1
max-connection = 256
mutex-slot = 32
proxy-concurrency = 2
server-name = flare-prod-slave-2
server-port = 12124
storage-type = tch
thread-pool-size = 16
