data-dir = /tmp/flare-staging-slave-1
index-servers = flarei-staging:12130
log-facility = local1
max-connection = 256
mutex-slot = 32
proxy-concurrency = 2
server-name = flare-staging-slave-1
server-port = 12132
storage-type = tch
thread-pool-size = 16
