
$LOAD_PATH.unshift(File.dirname(__FILE__)+"/../lib")

require 'flare/tools'

version = Flare::Tools::VERSION
flaretools = "flare-tools"

task :default => [:build]

task :build do |t|
  sh "(cd #{flaretools} && debuild -us -uc)"
end

task :debclean do
  sh "(cd #{flaretools} && debclean)"
end

