
$LOAD_PATH.unshift(File.dirname(__FILE__)+"/../lib")

require 'flare/tools'

flaretools = "flare-tools"

task :default => [:build]

task :build do |t|
  sh "(cd #{flaretools} && debuild -us -uc)"
end

task :debclean do
  sh "(cd #{flaretools} && debclean)"
end

task :change do
  puts "================================="
  puts "  Flare::Tools::VERSION = #{Flare::Tools::VERSION}"
  puts "================================="
  sh "(cd #{flaretools} && dch -i)"
end

task :clean => [:debclean] do
  sh "rm -f *.dsc *.tar.gz *.build *.changes"
end

task :cleanall => [:clean] do
  sh "rm -f flare-tools/debian/changelog.dch"
end

