# Flare configuration file
data-dir /var/lib/flare
log-facility local0
thread-type single
thread-pool-size 1
pid-file /tmp/flared.pid
server-name old-server
server-balance 50
server-partition 0
# replication settings will be added/updated below