data-dir = /tmp/flared3
index-servers = flarei:12120
log-facility = local1
max-connection = 256
mutex-slot = 32
proxy-concurrency = 2
server-name = flared3
server-port = 12123
storage-type = tch
thread-pool-size = 16